name: "Automatic Issue Labeling"

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add label automatically
        uses: actions/github-script@v7
        with:
          script: |
            const { issue, repository } = context.payload;
            const owner = repository.owner.login;
            const repo = repository.name;
            const author = issue.user.login;

            console.log(`Issue #${issue.number} opened by ${author}`);

            const { data: collaborators } = await github.rest.repos.listCollaborators({
              owner,
              repo,
              affiliation: "all"
            });

            const isCollaborator = collaborators.some(c => c.login === author);
            const labelToAdd = isCollaborator ? "INTERNAL" : "COMMUNITY";

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: issue.number,
              labels: [labelToAdd]
            });

            console.log(`Added label ${labelToAdd} to issue #${issue.number}`);
